const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{spawnSync}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE),dir=__dirname,python=process.argv[2],scripts=process.argv[3];
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
async function download(id,name){const wait=page.waitForEvent('download');await page.locator(id).click();const d=await wait,file=path.join(dir,name+'.json');await d.saveAs(file);return file;}
function validate(file,name,confirmed){const code="import sys;sys.path.insert(0,sys.argv[1]);import organize as o;o.validate_plan(o.read(sys.argv[2]),o.read(sys.argv[3]),sys.argv[4]=='true')";const r=spawnSync(python,['-B','-c',code,scripts,path.join(dir,name+'-catalog.json'),file,String(confirmed)],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);}
await page.goto(pathToFileURL(path.join(dir,'small.html')).href);assert.equal(await page.locator('article[data-gid]').count(),12);
await page.locator('[data-select="1"]').check();await page.locator('#series-name').fill('New group');await page.locator('#assign').click();assert.equal(await page.locator('h2').filter({hasText:'New group'}).count(),1);await page.locator('#undo').click();assert.equal(await page.locator('h2').filter({hasText:'New group'}).count(),0);
await page.locator('#independent').click();await page.locator('[data-move="up"][data-gid="1"]').click();
await page.locator('#search').fill('Chapter 1');const draft=await download('#draft','draft');assert.equal(JSON.parse(fs.readFileSync(draft)).items.length,12);validate(draft,'small',false);
await page.reload();await page.locator('#import').setInputFiles(draft);await page.locator('#message').filter({hasText:'进度已恢复'}).waitFor();const restored=await download('#draft','restored');assert.deepEqual(JSON.parse(fs.readFileSync(restored)),JSON.parse(fs.readFileSync(draft)));
const bad=JSON.parse(fs.readFileSync(draft));bad.items[0].title='changed';const badfile=path.join(dir,'bad.json');fs.writeFileSync(badfile,JSON.stringify(bad));await page.locator('#import').setInputFiles(badfile);await page.locator('#message').filter({hasText:'不匹配'}).waitFor();
await page.locator('#confirm').check();const confirmed=await download('#export','confirmed');validate(confirmed,'small',true);
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(dir,'mobile.png')});
const start=Date.now();await page.goto(pathToFileURL(path.join(dir,'large.html')).href);assert.equal(await page.locator('article[data-gid]').count(),3000);const largeMs=Date.now()-start;
await page.locator('#search').fill('Synthetic Work 749 Chapter 0');assert.equal(await page.locator('article[data-gid]:not([hidden])').count(),1);await page.locator('#confirm').check();const large=await download('#export','large-confirmed');validate(large,'large',true);assert.equal(JSON.parse(fs.readFileSync(large)).gidOrder.length,3000);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
const report={passed:true,counts:[12,3000],largeLoadMs:largeMs,checks:['group','ungroup','undo','move','filtered-full-export','draft-restore','title-tampering-rejected','single-confirmation','python-validation','mobile-width'],errors,requests};fs.writeFileSync(path.join(dir,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();})().catch(e=>{console.error(e);process.exitCode=1;});
